### ISSUE TITLE
Demo.gif is HUGE!

### ISSUE THREAD

**Issue by AlecDusheck** [jeremynoesen/homebridge-dyson-bp01#9]
Hey,

https://github.com/jeremynoesen/homebridge-dyson-bp01/blob/main/img/Demo.gif is like a 50mb file, would it be possible to upload this elsewhere so cloning this doesn't take a massive amount of time?

**Comment by jeremynoesen** [comment]
I would like to keep this in the repository, as this is how I handle all my other repositories. As a workaround, you can fork the repo on GitHub, delete the file from GitHub, then clone it. I know this is not the most ideal solution, but it should work.

**Comment by jeremynoesen** [comment]
If you are planning to fork this repo to submit a pull request, I recommend waiting a week or so, as I am in the middle of a kinda large refactor.
